config:
  mesh_file: "./resources/bunny.obj"
  coarse_mesh_files: ["./resources/coarse_1.obj", "./resources/coarse_2.obj", "./resources/coarse_3.obj"]
  diagnostics_viz: "./outputs/diagnostics.png"
  vtu_file: "./outputs/bunny_model.vtu"
  verbose: false
  do_extensive_visuals: false

utils:
  normalization_eps: 1E-12
  prolongation_neighbors: 3
  knn_graph_neighbors: 9

correctorGNN:
  hidden_layers: [128, 128, 128]
  dropout: 0.0

multigridGNN:
  epochs: 5000
  learning_rate: 0.001
  corrector_scale: 1
  weight_residual: 5.0
  weight_orthogonal: 10.0
  weight_projection: 0.001
  gradient_clipping: 1.0
  weight_decay: 0.00001
  log_every: 250

runner:
  n_modes: 128
  hierarchy: [256, 512, 1024]
  k_neighbors: 4
