config:
  verbose: true

utils:
  normalization_eps: 1E-12
  prolongation_neighbors: 1
  knn_graph_neighbors: 4

correctorGNN:
  hidden_layers: [128, 128, 128]
  dropout: 0.0

multigridGNN:
  epochs: 5000
  learning_rate: 0.001
  corrector_scale: 0.01
  weight_residual: 5.0
  weight_orthogonal: 10.0
  weight_projection: 0.001
  gradient_clipping: 1.0
  weight_decay: 1E-6
  log_every: 250

runner:
  mesh_file: "bunny_obj"
  n_modes: 128
  hierarchy: [256, 512, 1024]
  k_neighbors: 4
